In [1]:
import numpy as np

In [2]:
x= np.array([22,33,44,55,78])

In [3]:
x.size

5

In [4]:
x.shape

(5,)

In [5]:
arr1d = np.arange(10)

In [6]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,333]])

In [8]:
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222,  333]])

In [9]:
arr2d.shape

(4, 3)

In [10]:
# arr2dreshape = np.arange(20).reshape(1,20)
# arr2dreshape = np.arange(20).reshape(20,1)
# arr2dreshape = np.arange(20).reshape(4,5)
# arr2dreshape = np.arange(20).reshape(5,4)
# arr2dreshape = np.arange(20).reshape(2,10)
arr2dreshape = np.arange(20).reshape(10,2)


In [11]:
arr2dreshape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [12]:
arr2dreshape.shape

(10, 2)

In [13]:
arr2dreshape.ndim

2

In [17]:
arr2dflat = arr2dreshape.reshape(20)

In [18]:
arr2dflat.shape

(20,)

In [20]:
arr2dreshape.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arr2dreshape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [23]:
arr2dreshape.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
arr2dreshape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [27]:
vector = np.array([10])

In [28]:
vector

array([10])

In [29]:
scalor = np.array(10)

In [30]:
scalor

array(10)

In [11]:
arr3d = np.arange(64).reshape(4,4,4)

In [34]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [37]:
arr3d[2,2,2]

42

In [40]:
arr3d[1,2,1]

25

In [41]:
arr3d[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
arr3d*2

array([[[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22],
        [ 24,  26,  28,  30]],

       [[ 32,  34,  36,  38],
        [ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62]],

       [[ 64,  66,  68,  70],
        [ 72,  74,  76,  78],
        [ 80,  82,  84,  86],
        [ 88,  90,  92,  94]],

       [[ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118],
        [120, 122, 124, 126]]])

In [43]:
arr3d/2

array([[[ 0. ,  0.5,  1. ,  1.5],
        [ 2. ,  2.5,  3. ,  3.5],
        [ 4. ,  4.5,  5. ,  5.5],
        [ 6. ,  6.5,  7. ,  7.5]],

       [[ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5],
        [12. , 12.5, 13. , 13.5],
        [14. , 14.5, 15. , 15.5]],

       [[16. , 16.5, 17. , 17.5],
        [18. , 18.5, 19. , 19.5],
        [20. , 20.5, 21. , 21.5],
        [22. , 22.5, 23. , 23.5]],

       [[24. , 24.5, 25. , 25.5],
        [26. , 26.5, 27. , 27.5],
        [28. , 28.5, 29. , 29.5],
        [30. , 30.5, 31. , 31.5]]])

In [44]:
arr3d+2

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25],
        [26, 27, 28, 29],
        [30, 31, 32, 33]],

       [[34, 35, 36, 37],
        [38, 39, 40, 41],
        [42, 43, 44, 45],
        [46, 47, 48, 49]],

       [[50, 51, 52, 53],
        [54, 55, 56, 57],
        [58, 59, 60, 61],
        [62, 63, 64, 65]]])

In [45]:
arr3d-5

array([[[-5, -4, -3, -2],
        [-1,  0,  1,  2],
        [ 3,  4,  5,  6],
        [ 7,  8,  9, 10]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26]],

       [[27, 28, 29, 30],
        [31, 32, 33, 34],
        [35, 36, 37, 38],
        [39, 40, 41, 42]],

       [[43, 44, 45, 46],
        [47, 48, 49, 50],
        [51, 52, 53, 54],
        [55, 56, 57, 58]]])

In [46]:
a = np.arange(25).reshape(5,5)

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
b = np.arange(25,50).reshape(5,5)

In [62]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [64]:
a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [65]:
a+b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [66]:
a-b

array([[-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25]])

In [67]:
a*b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [68]:
a/b

array([[0.        , 0.03846154, 0.07407407, 0.10714286, 0.13793103],
       [0.16666667, 0.19354839, 0.21875   , 0.24242424, 0.26470588],
       [0.28571429, 0.30555556, 0.32432432, 0.34210526, 0.35897436],
       [0.375     , 0.3902439 , 0.4047619 , 0.41860465, 0.43181818],
       [0.44444444, 0.45652174, 0.46808511, 0.47916667, 0.48979592]])

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
sliceA = a[4,:3]

In [91]:
sliceA.ndim

1

In [92]:
sliceA

array([20, 21, 22])

In [84]:
indexA = a[2,3]

In [85]:
indexA

13

In [86]:
indexA.ndim

0

In [93]:
a>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [94]:
mask  = a<10

In [95]:
mask

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [96]:
a[mask]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a[mask] = 34

In [98]:
a

array([[34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
np.where(mask,100,a)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [106]:
a[(a%2 == 0) & (a%7 == 0)]

array([14])

In [105]:
a

array([[34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
np.concatenate((a,b))

array([[34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [109]:
np.concatenate((a,b), axis=1)

array([[34, 34, 34, 34, 34, 25, 26, 27, 28, 29],
       [34, 34, 34, 34, 34, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [110]:
np.hstack((a,b))

array([[34, 34, 34, 34, 34, 25, 26, 27, 28, 29],
       [34, 34, 34, 34, 34, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [111]:
zeros = np.zeros((5,7))

In [112]:
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [113]:
ones = np.ones((9,3))

In [114]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [116]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [117]:
l=[1,2,3,4]

In [118]:
np.array(l)

array([1, 2, 3, 4])

In [135]:
arrange= np.arange(1,100,10)

In [136]:
arrange

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [137]:
arrange.shape

(10,)

In [124]:
x=np.zeros((10,10))

In [125]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [129]:
y=x.reshape(2,2,5,5)

In [130]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [131]:
y.shape

(2, 2, 5, 5)

In [139]:
y.dtype

dtype('float64')

In [140]:
y.ndim

4

In [141]:
a = np.random.randn((10))

In [142]:
b = np.random.randn((10))

In [143]:
a

array([ 0.24327741, -0.24908384, -0.74538807,  0.1290766 ,  0.47250497,
       -1.39713056, -1.21723623,  0.08571539, -1.56547672,  0.52314244])

In [144]:
b

array([-0.9794358 , -1.64866079,  0.1353197 , -1.11381205, -2.08350402,
       -0.79086451,  1.33222139,  1.27434135, -2.09279509,  1.13656754])

In [145]:
a+b

array([-0.73615839, -1.89774464, -0.61006838, -0.98473545, -1.61099905,
       -2.18799507,  0.11498516,  1.36005674, -3.65827181,  1.65970997])

In [146]:
a-b

array([ 1.22271322,  1.39957695, -0.88070777,  1.24288866,  2.55600898,
       -0.60626605, -2.54945762, -1.18862596,  0.52731837, -0.6134251 ])

In [147]:
2*a

array([ 0.48655482, -0.49816768, -1.49077614,  0.25815321,  0.94500994,
       -2.79426112, -2.43447246,  0.17143078, -3.13095345,  1.04628488])

In [148]:
a>0

array([ True, False, False,  True,  True, False, False,  True, False,
        True])

In [149]:
a[a>0]

array([0.24327741, 0.1290766 , 0.47250497, 0.08571539, 0.52314244])

In [150]:
x = np.array([1,7,9,8,5])

In [151]:
x[4]

5

In [158]:
x[x>5]

array([7, 9, 8])

In [159]:
x[[2,1]]

array([9, 7])

In [3]:
x

array([22, 33, 44, 55, 78])

In [4]:
[n*2 for n in x]

[44, 66, 88, 110, 156]

In [7]:
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222,  333]])

In [8]:
arr2d.shape

(4, 3)

In [9]:
arr2d/10

array([[1.000e-01, 2.000e-01, 3.000e-01],
       [1.100e+00, 2.200e+00, 3.300e+00],
       [1.110e+01, 2.220e+01, 3.330e+01],
       [1.111e+02, 2.222e+02, 3.330e+01]])

In [12]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [19]:
arr3d[2,1,2]

In [20]:
arr3d[2,1,2]  = arr3d[2,1,2]*2

In [21]:
arr3d[2,1,2]

76

In [22]:
x

array([22, 33, 44, 55, 78])

In [26]:
y = np.arange(5)

In [27]:
y

array([0, 1, 2, 3, 4])

In [28]:
x+y

array([22, 34, 46, 58, 82])

In [29]:
a = np.arange(25)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
#mirroring = element wise operation
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [34]:
a + b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [35]:
a * b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [36]:
c = np.arange(20).reshape(5,4)

In [37]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
b@c

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])